### DISCUSSION TITLE
Application.yml 나눌까요?

### DISCUSSION THREAD

**Discussion by thelightway24** [talkpick/talkpick-backend#25] [General]
개발을 진행하면서 속성 값 같은 설정들은 application.yml로 분리하자는 방향에는 어느 정도 합의가 된 것 같습니다.

그런데 설정을 하나씩 yml로 옮겨가다 보니, 전체 yml 파일이 점점 길어지고 개발자별로 작성한 설정도 섞이게 되어
파일이 복잡해지고 관리가 어려워지는 문제가 생기는 것 같습니다.

특히, 개발 영역은 서로 다른데 동일한 yml 파일을 수정하다 보니
Git 충돌이 자주 발생하는 이슈도 이미 몇 차례 겪었습니다.

그래서 설정을 목적별로 분리된 yml 파일로 나누어 관리하는 방식을 도입해보면 어떨까 제안드립니다.

Spring Boot 2.4 이상부터는 다음과 같이 application.yml에서 외부 설정 파일들을 import로 분리해서 관리할 수 있다고 합니다.

``` yaml
# 예시
spring:
  config:
    import:
      - classpath:/database-config.yml
      - classpath:/etc-config.yml
``` 

만약 좋다고 하시면 다른 환경에서 테스트 해보고 도입하겠습니다.

**Comment by HaechangLee** [comment]
좋은 방식이라고 생각합니다.
그런데 import 파일을 동시에 추가하면 여전히 conflict가 날 것 같습니다.
```
spring:
  config:
    import:
      - classpath:/config/   # config 폴더 아래의 모든 yml을 로드
```
이런식으로 import 폴더를 지정해서 그 안의 yml 파일을 읽게 끔 지정하면 conflict가 없을 것 같은데 어떻게 생각하시나요?
